- filtres/nou.py
- settings_sample.py
Proposta esmentada a #45 per fer més explícit el comportament del filtre per a tiquets nous que tria valors per defecte segons algunes capçaleres del correu:
* Les capçaleres a tractar són part de la configuració, per tant se'n poden triar d'altres.
* Els valors a buscar són expressions regulars.
* S'avaluen les condicions en ordre i es retornen els valors per defecte de la primera que casa.
La configuració de l'exemple és l'equivalent a la que hi havia anteriorment, amb les capçaleres que s'utilitzaven implícitament en el codi de la classe FiltreNou.
> Refactoritza la configuració de valors_defecte

- netejahtml.py
Als testos ja tenia un mail amb un bloc PGP, aixi que he afegit una nova operacio a netejahtml per esborrar aquests blocs i un test per comprovar que ho fa correcte.
Els metodes de netejar HTML encara no s'utilitzen al mailtoticket, s'ha de veure quina seria la millor forma de que siguin configurables
> Afegeixo metode per netejar el bloc de PGP d'un mail

- mailticket.py
He descobert que un dels test no passava. Un dels mails de prova te un altre mail com a attachment. Aquest mail attachat te part text i part html. Per tant, el mail original té 2 attachments.
Mailtoticket es menjava els attachments perque no considerava possible tenir un attachment sense un nom de fitxer que no fos una imatge. He tret aquesta comprovació perque era innecessaria.
Per ser 100% puristes, el mail hauria de tenir un sol attachment, ja que es tracta d'un multipart alternative. Aixo implicaria canviar el tractament que faig dels alternatives, pero crec que un canvi prou radical com per començar amb aquest petit canvi que com a minim fa que no es perdi informació al tractar el mail.
> Permeto attachments sense filename que no siguin imatges

- mailtoticket.sh
Aquest canvi afegeix el virtualenv al PATH tal com s'ha recomanat al [README](README.md) per assegurar que es trobaran les dependències del programa en el moment de l'execució, independentment del _shell_ que s'utilitzi per cridar l'script.
Per exemple, pot haver-hi diferències entre executar-lo des del _cron_ o des del _shell_.
> Afegeix el virtualenv recomanat al PATH

- mailtoticket.py
Aquest canvi fa que sempre s'afegeixi la capçalera `X-Mailtoticket` al correu sortint perquè es pugui identificar com un correu processat i d'aquesta manera evitar bucles.
Una cosa important a tenir en compte és que ara la capçalera retorna el valor `SUCCESS` quan tot va bé, enlloc del xurro alfanumèric que retornava fins ara. Això afectarà aquelles instàncies que compten amb aquest valor sigui un de determinat en els seus filtres de Maildrop.
> Fix SMTP loops (closes #61)

- correu.py
- mailtoticket.py
Adjunta el correu original als informes d'error i a més a més indica en els logs quin és el `Message-Id` tant si ha pogut enviar-lo com en cas contrari.
Resol #54.
> Attach original mail

- filtres/nou.py
Per poder solucionar #81, hem de permetre sobreescriure tots els paràmetres amb paràmetres addicionals, perque tal i com ho teniem (parametres posicionals + parametres via diccionari), python dona error.
Ara omplim un diccionari amb els paràmetres que abans eren posicionals i després sobreescrivim amb els addicionals del diccionari.
> Permetre sobreescriure tots els parametres amb parametres addicionals

- mailtoticket.sh
Amb la introducció dels codis de sortida no té sentit forçar
que el mailtoticket.sh avorti si falla qualsevol ordre que
s'executi. Abans ho utilitzàvem per detectar si no es trobava
el sendmail o el $HOME.
> Evita que avorti si mailtoticket.py dóna error

- correu.py
- filtres/reply.py
- mailtoticket.py
A partir d'uns avisos del CodeClimate hem detectat que fem servir
en alguns fitxers la sintaxi 'except E, e', que està desaconsellada
a partir de python 2.6. Es recomana canviar-la per 'except E as e'.
Més detalls a http://stackoverflow.com/a/2535770/1314986
> Actualitzo a sintaxi recomenada de 'except'

- .codeclimate.yml
Configurem l'engine 'radon' per a què comprovi la sintaxi de
Python 2, ja que per omissió comprova la de Python 3.
Veure l'apartat "Python Version" de la documentació de
CodeClimate: https://docs.codeclimate.com/docs/radon
> Configurar CodeClimate per forçar python 2

- filtres/nou.py
- filtres/reply.py
- soa/service.py
- test/test_service.py
L'objectiu d'aquesta branca és començar a encapsular l'estructura interna del resultat d'una crida a SOA, que actualment es comprova amb l'expressió `resultat['codiRetorn']`.
Aquest PR encapsula l'ús duplicat d'aquesta expressió que hem detectat en els warnings del CodeClimate, en els següents fitxers: 
* `filtres/nou.py` (línies 72 i 101)
* `filtres/reply.py` (línia 90)
La refactorització implica encapsular l'expressió actual en un nou mètode `resultat_erroni` que estarà definit en un únic lloc (la classe `SOAService`).
> Encapsulament de la comprovació d'errors SOA

- README.md
Havíem posat la URL via ssh, que només serveix per a les persones que tenen accés d'escriptura al repo. És millor posar la URL via https i en tot cas, qui vulgui ssh ja sap com fer-ho.
> Utilitza la URL pública del repo

- check-qa.sh
Si el pep8 no està instal·lat avisa però no dóna error.
Closes #105
> Millora l'script de comprovació de qualitat

- settings_sample.py
Corregeix una referència al codi de l'usuari extern, que ha de ser el nom.
De passada indica el mateix usuari extern per defecte als dos exemples existents.
> Indica l'usuari extern general per defecte

- mailtoticket.py
Avoids breaking message format when using procmail or other
MDA having each message starting with 'From ' (à la mbox),
as reported in #26.
> Append message header cleanly

- settings.py
Als ultims testos s'ha fet un canvi de paràmetre de configuració per un test concret accedint directament a l'objecte settings. Funciona, pero Eclipse es queixa de que la variable no està visible.
Hem afegit un "set" a la configuració per poder canviar-ho de forma més elegant i per ser coherents amb el "get" que tenim per accedir al valor d'un paràmetre.
Faig també una PR als testos amb el canvi corresponent.
> Afegeixo un setter al config per poder canviar paràmetres ja carregats

- filtres/reply_reobrint.py
- mailtoticket.py
Combining string formats and concatenation with the + operator
brings errors like this:
```
TypeError: not all arguments converted during string formatting
```
> Fix string concatenation

- mailticket.py
- requirements.txt
- settings.py
- settings_sample.py
- test/test_mailticket.py
Add support for regexes in `mails_no_ticket` setting while preserving old plain strings compatibility.
Closes #108
> Support regexes in mails_no_ticket

- mailticket.py
Quan un header pot contenir un mail, el nostre codi retorna únicament l'adreça de mail i no altres coses que hi pugui haver davant. Faltaven les més importants: To, Cc i Bcc
Amb aixo ens podem estalviar expressions regulars complexes a l'hora de validar les adreces
> Afegim els headers que falten que poden contenir mails

- filtres/reply.py
- soa/tiquets.py
- test/test_reply.py
Tractem el cas d'un comentari d'un usuari que te un ticket creat amb un mail diferent del seu oficial i que contesta des d'aquest mail.
Si aquest usuari fa un reply des d'aquet mail no conegut, quedava fins ara com a usuari extern i se li enviava una notificació. Ara detectem que es tracta del mateix usuari perque coincideix el mail i per tant no queda com a extern i no cal enviar-li notificació.
> Tenim en compte el mail del ticket quan tractem un reply

- soa/identitat.py
Fem que si no existeix, retorni com a valor per defecte None.
Tot el problema es que quan estem buscant a quin usuari correspon una adreça, busquem de totes les seves identitats quina es la que te l'adreça com a adreça preferent. El problema es que hi ha identitats que no tenen ni mail i aixo fa petar la cerca sense retornar cap usuari.
> Si identitat no respon amb un camp emailPreferent, no ha de petar

- soa/identitat.py
He canviat bastant la forma com obtenim un mail remot per que la gent que té mails de departament no té normalment els seus mails upc registrats a identitat digital.
Hem trobat el cas d'una persona que només tenia el seu compte upc en un compte genèric que havia demanat (i que no es el seu) aixi que per evitar aixo primer mirem pels mails @upc.edu si la part de l'esquerra correspon a un usuari i si es aixi, es aquest i punt.
En cas contrari, continuem amb el que feiem fins ara, pero sent mes agressius i retornant "None" en cas de no detectar cap email preferent quan hi ha més d'una persona.
> Canvis per primer mirar si la part anterior a @upc.edu es un usuari real

- netejahtml.py
Teniem un codi que extreia els blocs de signatura PGP, pero quan teniem <BR> al final de línia el patró no era prou flexible. Ara ja serveix en ambdos casos
> Permetem tenir un <br> a final de linia del PGP BLOCK

- correu.py
Quan en els logs hi havia accents (per exemple, perque apareixen al subject o al codi d'error que retorna el bus SOA) el correu no es podia enviar. Si especifiquem la codificació, evitem aquest problema
> Afegim l'encoding quan enviem un mail per evitar problemes amb accents

- mailticket.py
- requirements.txt
- test/test_mailticket.py
Quan la capçalera Date està en un format no estàndard, no es crea el tiquet i es genera un informe d'error.
S'ha detectat aquest comportament amb missatges creats amb "Apple Mail". L'error es produeix al mètode MailTicket.get_date().
Com que la data només es fa servir a títol indicatiu, es proposa que, quan MailToTicket no pugui parsejar la data del missatge, es faci servir la data actual del sistema (vegeu https://demana.upc.edu/mailtoticket/tickets.php?id=48).
> Acceptar mails amb capçalera «Date» en format no estàndard

- test/test_mailticket.py
Fa uns dies que al veure la solució del mocking pel tema de fer proves de fitxers i em va semblar molt estrany. He fet un canvi per fer servir StringIO, que de fet es exactament el que fa la funcio email.message_from_text. El codi es mes simple i entenedor.
Ara tal i com està el codi, podem fer servir la funció testhelper.llegir_mail si volem llegir un fitxer o bé lo fer un MailTicket(StringIO(string)) si volem fer servir un string amb el mail. En els dos casos els testos queden mes simples
> Canvio el mock per StringIO als testos

- mailticket.py
- test/mails/mailauto.txt
- test/test_mailticket.py
Al DAC hem detectat que les respostes automàtiques del vacation de sieve es processaven com a tiquets nous i hem fet aquest petit canvi que evita que aquests correus es processin.
Abans d'acceptar la proposta de canvi, m'agradaria afegir algun test i una mica més de documentació. Creo la proposta ara per veure si passa els tests però ja avisaré quan estigui llesta per integrar amb master.
> Skip Auto-Submitted messages (e.g. vacation)

- mailticket.py
Es un altre tipus de mail de confirmació de lectura i està comprovat que no tenen cap capçalera que ho indica
> No tractem els mails que tenen al subject "leer informe :"

- filtres/filtre.py
Tenim un cas d'ús de mail provinent d'un formulari de genweb on el from es un mail genèric i el reply-to es el que ens indica quin es l'usuari.
S'ha canviat el codi per primer mirar si a partir el reply-to podem saber quin usuari es i si existeix, fem servir aquest. Si no, fem servir el del from (que serà el cas habitual)
De fet, estavem fent servir el reply-to com a mail per enviar les notificacions, aixi que es lògic que també el fem servir per calcular l'usuari solicitant.
> Si hi ha "reply-to" el mira abans del "from" per trobar el solicitant

- filtres/filtre.py
Simplement he vist que des de que he posat el comentari, no se m'executa correctament perque no tenia especificat que era UTF8
> Faltava la capçalera UTF per no tenir problemes amb comentaris

- filtres/nou.py
Quan creem un ticket, en una segona fase modifiquem el ticket. Segons el codi actual, es tornava a modificar l'email solicitant per posar el from_or_reply_to, pero aixo es un error perque quan el ticket es crea, pot ser que sobreescrivim el from_or_reply_to per algun valor per defecte posat al fitxer de configuració.
Per exemple, suposem un mail automàtic "reserves@exemple.com" que sabem que ha de generar un ticket com a "persona@exemple.com". Amb el codi actual, aixo es perdia i el ticket quedaria amb el mail de contacte "reserves@exemple.com"
> Bug sobreescriure email solicitant

- settings.py
Quan no existeix el fitxer settings_default.py amb els valors
per defecte, els inicialitzem sense cap valor. Això és útil per
als tests, que no necessiten tenir cap valor per defecte.
> Inicialitza els settings buits si troba el fitxer

- .travis.yml
- check-qa.sh
- mailticket.py
- mailtoticket.py
- netejahtml.py
- settings.py
- settings_sample.py
- soa/identitat.py
- test/test_import.py
- test/test_mailticket.py
- test/test_neteja.py
- test/test_reply.py
- test/test_service.py
pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.
> Replace pep8 with pycodestyle

- mailtoticket.py
It may be convenient to know exactly what happened when an error is found, thus exiting with a different exit status for each kind of error.
Since both SUCCESS and SKIP are not considered errors, both keep returning exit status 0. Therefore, this change should not break backwards compatibility with MailToTicket instances running via fetchmail.
Thanks: Oleg Rajnovic (UPCnet)
> Return different exit status for errors

- requirements.txt
- settings_sample.py
- soa/identitat.py
Fem els canvis a identitat.py per donar suport a la nova api rest. Aixo implica una nova llibreria (requests) per fer les peticions i un nou paràmetre (identitat_digital_apikey) necessari per autenticar-se
> Canvis per donar suport a la nova API REST

- netejahtml.py
```
$ pycodestyle .
netejahtml.py:140:9: E741 ambiguous variable name 'l'
netejahtml.py:170:9: E741 ambiguous variable name 'l'
netejahtml.py:219:9: E741 ambiguous variable name 'l'
```
See: https://travis-ci.org/github/UPC/mailtoticket/builds/692590499
> Fix errors reported by pycodestyle-2.6.0

- .dockerignore
- Dockerfile
- README.md
> Dockerfile for dockerize application

- Dockerfile
Altrament el fitxer de dependències no estarà disponible.
> Copia el directori abans d'executar el pip

- mailticket.py
Ens ha creat un ticket a partir d'un mail automàtic que començava per "Llegit:" i que mailtoticket no ha detectat. Hem afegit aquest patró a la llista
> Afegim el patro "Llegit:" per considerar el missatge automatic

- .gitignore
- .travis.yml
- Dockerfile
- README.md
- buscamail.py
- buscaticket.py
- ldaphelper.py
- mailticket.py
- mailtoticket.py
- netejahtml.py
- requirements.txt
- soa/identitat.py
- test/test_mailticket.py
- test/test_neteja.py
- test/test_reply.py
- test/testhelper.py
Canvis per suportar el pas a Python 3. A part dels canvis mes o menys mecanics, hi ha tota una part relacionada amb els encodings que ha costat una mica més.
Per fer aixo amb seguretat, s'han de passar també els testos interns, dels que també tenim una branca migracio-python3
> Migracio python3

- soa/identitat.py
Amb la implementació actual, quan un mail es @upc.edu, es mira si correspon a una persona, pero pot ser que sigui un mail generic com per exemple fib.cap.estudis. En aquest cas entrariem a la segona part on buscariem identitats que tinguin aquest mail, pero resulta que el mail oficial es cap.estudis@fib.upc.edu i per tant no trobariem identitat amb aquest mail.
Clarament aixo es un error, que solucionem simplement fent una consulta a identitats a partir del cn i si correspon a alguna, aquesta es la identitat a nom de la qual s'ha de crear el ticket
> Fem que funcionin els mails genèrics que no son son personals

- filtres/nou.py
A la instancia de UTGCNTIC tenim molts alies de la bustia gestionada per mailtoticket i moltes regles que classifiquen el ticket en funció del mail al que s'ha enviat. Per veure errors en aquestes regles, es molt útil que al missatge aparegui no només qui ha enviat el mail i a quina hora, sino també a quina adreça l'ha enviat.
> Afegim al ticket el mail al qual s'ha enviat

- filtres/nou.py
- filtres/nou_extern.py
Quan es crea un ticket, s'envia un missatge de creació al solicitant amb un link al ticket per poder fer el seguiment i un missatge genèric.
En el cas d'un ticket creat amb un mail extern que no es mapeja a cap usuari UPC, aquest missatge es una mica absurd ja que no li donem cap informació útil i un link a on no pot accedir.
Per tant, es més lògic que aquest mail no s'envii quan es un usuari extern
> No enviem missatge de creació als externs

- README.md
Calia actualitzar la URL de la icona després de migrar la configuració de travis-ci.org a travis-ci.com.
He seguit les instruccions indicades a https://docs.travis-ci.com/user/status-images/
> Actualitza imatge amb estat del build de Travis

- .github/workflows/python-app.yml
- README.md
Aquest PR configura el repo per tal d'executar els mateixos checks que tenim ara amb el Travis, però contra GitHub Actions.
La configuració del build és equivalent a la que tenim ara mateix per al Travis.
> Configuració de GitHub Actions

- filtres/filtre.py
Tracta l'excepció TypeError en codificar un attachment que és detectat
com un string i no com una seqüència de bytes (bytes-like).
Fixes #214
> Tracta TypeError en base64.b64encode()

- mailticket.py
- test/mails/mailauto.txt
- test/test_mailticket.py
Permetro el parametre mails_sempre_ticket, per indicar una llista de mails que han de poder crear ticket encara que estiguin marcats com automàtics
Ja ho havia demanat (i implementat!) en una altra pull request ( #172 ) Haviem trobat una solució externa que al final no ha estat prou flexible.
> Feature mails sempre ticket

- .travis.yml
- README.md
Refà #217 ja que es va tornar als enllaços antics amb #218.
> Actualitza de nou els enllaços a Travis

- netejahtml.py
No s'estava detectant la signatura de gmail (bloc gmail_signatura) i els mails citats tenien una etiqueta incorrecta (gmail_extra en comptes de la correcta, gmail_quote).
> Detecció de signatura i mails citats a gmail al fer la neteja

- mailtoticket.py
En un principi, podiem utilitzar mailtoticket com a filtre de maildrop en servidors propis de mail i era interessant tornar a escriure per la sortida el mail original amb una capçalera extra per dir que havia fet el mailtoticket amb el missatge.
Actualment només fa falta el codi d'error i aquest print només es soroll. Hem afegit un paràmetre per desactivar aquesta funcionalitat mantenint la compatibilitat, tot i que potser seria útil fer una enquesta per veure si encara cal arrossegar aixo o bé podem directament eliminar aquesta forma de funcionament i simplificar codi.
> Afegim parametre per no imprimir el mail per stdout

- filtres/nou.py
- mailticket.py
- test/mails/cc.txt
- test/test_regles.py
Volem permetre regles per canviar els valors per defecte basades en capçaleres que poden tenir més d'un valor, com per exemple, les Cc.
Per fer aixo, varem un test per veure que efectivament només s'agafa el primer valor i després implementarem els canvis necessaris per obtenir tots els valors d'una capçalera i tenir-los en compte al motor de regles
> Permetre que les regles funcionin amb capçaleres multivaluades

- .github/workflows/python-app.yml
- .travis.yml
- mailticket.py
A partir de Python 3.8, la comparació amb literals
no s'hauria de fer amb 'is' sinó amb '=='.
Veure [més detalls](https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior).
> fix: compara literals amb '=='

- .readthedocs.yaml
Fa temps que falla el build dels docs a mailtoticket.readthedocs.io,
segurament des de què vam afegir suport per LDAP ja que necessita que
hi hagi instal·lades les dependències de compilació.
Ara he indicat un fitxer de requisits independent per als docs, que no
conté res i no hauria de donar problemes.
https://docs.readthedocs.io/en/stable/config-file/v2.html
> Corregeix la configuració d'sphinx
