- filtres/nou.py
- soa/tiquets.py
Canvis per permetre utilitzar les millores incoporades a la api v5: informar del mail del solicitant al moment de la creació del ticket.
A hores d'ara em fa el tonto amb els salts de linia. Deixo la PR feta, pero s'ha de solucionar aixo
> Canvi api v5

- filtres/nou.py
- filtres/reply.py
Per millorar els logs que arriben als gestors de tickets, hem posat el codi d'error a part del missatge que ens arriba via API. Sospitem que no tots els codis d'error tenen missatge.
> Afegim codi d'error

- LICENSE
- README.md
Aquest canvi inclou la llicència AGPL-3.0 tal com vam acordar i el text legal corresponent al README.
> Afegeix la llicència i el copyright (closes #8)

- mailtoticket.py
Retorna 0 en cas que l'estat sigui _SUCCESS_ o _SKIP_ i 1 altrament.
Resol #38.
> Set exit status (closes #38)

- mailtoticket.py
Afegeix la informació de l'identificador del missatge als logs, de forma que es pugui localitzar més fàcilment.
Resol #52.
> Afegeix el Message-ID al log

- mailtoticket.py
He afegit el PID al format del logger. Resol #53.
> Afegeix el PID als logs (closes #53)

- soa/identitat.py
Solucionem aixo https://github.com/UPC/mailtoticket/issues/73
Al commit també hi ha problemes d'espais. Cal separar-ho en dos?
> Busquem primer el mail a llista, despres a remot i despres a patrons

- filtres/nou.py
- filtres/reply.py
- mailticket.py
- netejahtml.py
Branca refactoritzada basada en #72 però sense els canvis de salt de línia.
> Neteja html refactoritzada

- filtres/nou.py
Hem acceptat el canvi d'abans tan rapid que no hem vist que hi havia un fallo!
> Faltaven uns ** al passar els parametres

- mailtoticket.py
Vaig introduir l'error al refactoring de 1a81830.
> Corregeix el codi de sortida

- .gitignore
- .travis.yml
- README.md
- test/test_import.py
Amb aquest esquelet bàsic activarem el Travis-CI.
> Prepara l'entorn per travis-ci

- .codeclimate.yml
Afegim el CodeClimate per poder tenir comprovacions automàtiques de la qualitat del codi.
> Afegida configuració per al CodeClimate

- .travis.yml
> Move tests before build step

- .travis.yml
- buscamail.py
- buscaticket.py
- correu.py
- filtres/__init__.py
- filtres/filtre.py
- filtres/nou.py
- filtres/nou_extern.py
- filtres/reply.py
- filtres/reply_reobrint.py
- filtres/reply_tancat.py
- mailticket.py
- mailtoticket.py
- netejahtml.py
- settings.py
- settings_sample.py
- soa/identitat.py
- soa/service.py
- soa/tiquets.py
- test/test_import.py
[PEP 0008](https://www.python.org/dev/peps/pep-0008/) són unes recomanacions d'estil de la comunitat de Python, que hem decidit utilitzar-les com a base per estandarditzar l'estil del codi i evitar errors habituals.
Aquesta proposta de canvis és el primer pas per complir les recomanacions i activar les comprovacions a Travis. Un cop acceptat aquest canvi, ens podrem posar a refactoritzar el codi sense preocupar-nos per les qüestions d'estil.
> Corregeix l'estil del codi per complir PEP8

- filtres/nou.py
- filtres/reply.py
> Importa SOAService on es necessita

- check-qa.sh
- pre-commit.sample
Indicacions per configurar el `pre-commit` i executar localment les comprovacions de qualitat.
> Comprova la qualitat en local

- soa/identitat.py
Soluciona aquesta issue
https://github.com/UPC/mailtoticket/issues/106
> Fix emailpreferent

- netejahtml.py
Fem que només esborri la linia de prefix de signatura si es pot fer de forma segura
> Fix reply prefix

- filtres/reply.py
- mailticket.py
Fixes two related issues: composing subject from fragments and matching subject in unicode.
Closes #114
> Match unicode subject

- filtres/nou.py
- filtres/reply.py
Tal i com estava, es netejavem les url que feien referència a attachments dintre del mail i per tant després no es feia la substitució.
Ara primer substituim i després netegem. L'ordre es correcte
> Fem la substitució de URL d'imatges abans de netejar

- netejahtml.py
Perque no es queixi amb els accents, afegeixo la capçalera de utf8
> Afegeixo capçalera de utf8

- filtres/reply_reobrint.py
Hi havia un string mal posat. Ara ja està corregit perque no peti si ha d'escriure l'error al log
Abans tenia una altra PR (https://github.com/UPC/mailtoticket/pull/130) , pero l'he liat molt i n'he fet una de nova
> El missatge d'error de reobrir no tenia be el %s

- filtres/reply.py
- test/test_reply.py
Fins ara el ticket-id s'havia d'obtenir del subject, amb la manca de fiabilitat que aixo suposa. Ara que ja tenim un message-id amb el ticket, podem obrenir-ho
> Obtinc ticket-id inicialment del message-id i afegeixo text

- filtres/reply.py
Em falta fer proves en local per no canviar la funcionalitat. No l'accepteu encara!
> Afegim un parametre per permetre dir si volem notificar els comentaris

- settings_sample.py
Tal i com comentava @aaguilera , faltava afegir un exemple
> Afegeixo exemple del parametre notificar_comentaris_afegits

- filtres/nou.py
Si ho netegem al principi, ens mengem les URL de les imatges i si ho fem al final, el mail de notificació no està net. S'ha de fer 2 vegades partint sempre del HTML original
Aixo soluciona aquesta issue https://github.com/UPC/mailtoticket/issues/159
> Netejo el html just quan creo el ticket i just quan actualitzo

- mailticket.py
- test/mails/mailbuit.txt
- test/test_mailticket.py
- test/testhelper.py
Es per solucionar aquesta issue https://github.com/UPC/mailtoticket/issues/162
> Evitem retornar None al cridar get_body

- netejahtml.py
- test/mails/reply-mutipart-alternative.txt
- test/test_neteja.py
Fem que es netegi el que hi ha dintre dels tags STYLE  i SCRIPT, per que si no pot quedar la part dels estils o de javascript com a contingut del mail
> Netegem el tag STYLE i SCRIPT amb el seu contingut i afegim un test

- mailticket.py
- test/mails/comentaris.txt
- test/mails/encoding-xungo.txt
- test/test_mailticket.py
- test/test_neteja.py
Tenia un text a mig pujar (desde feia mesos) i un de nou per un tema d'encoding que he solucionat a la classe mailticket.py
> Afegim un parell de testos

- README.md
Acaba de polir un parell de detallets abans de publicar la versió 3.
> Prepara la versió 3

- filtres/filtre.py
- filtres/nou.py
- mailticket.py
- soa/tiquets.py
- test/test_mailticket.py
- test/test_nou.py
Faig una pull request nova i anulo la #186, que partia d'una branca amb molts altres canvis
> Feature afegir solicitants addicionals

- filtres/nou.py
- mailticket.py
Originalment detectat a [travis](https://app.travis-ci.com/github/UPC/mailtoticket/jobs/527066352#L299).
> Corregeix els avisos del pycodestyle
